version: "3.7"

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "10m" 

services:
  mailserver:
    <<: *default-opts
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: vandal.services
    volumes:
      - maillogs:/var/log/mail/
      - ./var/mail/:/var/mail/
      - ./var/mail-state/:/var/mail-state/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/certbot/certs/:/etc/letsencrypt/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - LOG_LEVEL=info
      - ENABLE_FAIL2BAN=0
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - SPOOF_PROTECTION=1
      - ENABLE_QUOTAS=1
    ports:
      - "25:25"
      - "465:465"
      - "993:993"
      - "587:587"
      - "143:143"
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
  
  certbot-cloudflare:
    container_name: mailserver-certbot
    image: certbot/dns-cloudflare:latest
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare-api-token -d mail.vandal.services
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt/
      - ./docker-data/certbot/logs/:/var/log/letsencrypt/
    secrets:
      - cloudflare-api-token

  certbot-cron:
    image: certbot/dns-cloudflare:latest
    container_name: certbot-cron
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt/
      - ./docker-data/certbot/logs/:/var/log/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - cloudflare-api-token
    entrypoint: "/bin/sh -c"
    command: >
      'echo "SLEEPTIME=$$(awk \"BEGIN{srand(); print int(rand()*(3600+1))}\");
      echo \"0 0,12 * * * root sleep $$SLEEPTIME && certbot renew --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare-api-token -q\" >> /etc/crontabs/root
      && crond -f'
      
volumes:
  maillogs:
    driver: local

secrets:
  cloudflare-api-token:
    file: ./docker-data/certbot/secrets/cloudflare.ini

### EXAMPLE
# Cloudflare API token used by Certbot
#dns_cloudflare_api_token = banana